baseURL = "https://passwordshamer.com/"
languageCode = "en-us"
title = "Password Shamer"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  tagline = "Shaming bad password requirements and practices everywhere."
  contributeTitle = "Contribute to this project"
  